const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const seedJobs = [
  {
    id: 'JYBL-2613',
    title: 'Production Officer / Executive / Assistant Manager',
    company: 'Confidential Pharma Employer',
    sector: 'Pharma Manufacturing',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '2-10 yrs',
    salaryRange: 'Compensation on request',
    type: 'Full-time',
    openings: 8,
    status: 'Open',
    location: 'Selaqui, Dehradun, Uttarakhand',
    description: 'Pharma manufacturing mandate for production profiles across officer, executive, and assistant manager levels. Relevant experience in granulation, compression, coating, capsule, QMS production, or related shop-floor operations is preferred.',
    salary: 'Compensation on request',
    tags: ['pharma manufacturing', 'production', 'dehradun'],
  },
  {
    id: 'JYBL-2614',
    title: 'Maintenance Engineer',
    company: 'Confidential Pharma Employer',
    sector: 'Engineering & Maintenance',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '2-10 yrs',
    salaryRange: 'Compensation on request',
    type: 'Full-time',
    openings: 7,
    status: 'Open',
    location: 'Selaqui, Dehradun, Uttarakhand',
    description: 'Hiring electrical, mechanical, utilities, water system, and AHU maintenance professionals for a regulated manufacturing setup. Candidates with pharma plant maintenance exposure are preferred.',
    salary: 'Compensation on request',
    tags: ['maintenance', 'electrical', 'mechanical'],
  },
  {
    id: 'JYBL-2615',
    title: 'QA Executive / Documentation Executive',
    company: 'Confidential Pharma Employer',
    sector: 'Quality Assurance',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '2-10 yrs',
    salaryRange: 'Compensation on request',
    type: 'Full-time',
    openings: 10,
    status: 'Open',
    location: 'Selaqui, Dehradun, Uttarakhand',
    description: 'Quality assurance openings covering IPQA, validation, line clearance, documentation, and batch-record support within pharmaceutical operations.',
    salary: 'Compensation on request',
    tags: ['qa', 'ipqa', 'documentation'],
  },
  {
    id: 'JYBL-2616',
    title: 'QC Analyst',
    company: 'Confidential Pharma Employer',
    sector: 'Quality Control',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '2-10 yrs',
    salaryRange: 'Compensation on request',
    type: 'Full-time',
    openings: 20,
    status: 'Open',
    location: 'Selaqui, Dehradun, Uttarakhand',
    description: 'Quality control roles available for RM/PM, FG, HPLC, documentation, stability, and microbiology functions. B.Sc, M.Sc, D.Pharma, B.Pharma, or M.Pharma backgrounds may be considered based on role fit.',
    salary: 'Compensation on request',
    tags: ['qc', 'hplc', 'microbiology'],
  },
  {
    id: 'JYBL-2617',
    title: 'HR Documentation Executive',
    company: 'Confidential Pharma Employer',
    sector: 'HR & Administration',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '2-10 yrs',
    salaryRange: 'Compensation on request',
    type: 'Full-time',
    openings: 1,
    status: 'Open',
    location: 'Selaqui, Dehradun, Uttarakhand',
    description: 'Support HR documentation, employee records, and administrative coordination for plant hiring and workforce operations.',
    salary: 'Compensation on request',
    tags: ['hr', 'documentation', 'plant hr'],
  },
  {
    id: 'JYBL-2618',
    title: 'Accounts Executive',
    company: 'Confidential Pharma Employer',
    sector: 'Accounts & Finance',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '2-10 yrs',
    salaryRange: 'Compensation on request',
    type: 'Full-time',
    openings: 3,
    status: 'Open',
    location: 'Selaqui, Dehradun, Uttarakhand',
    description: 'Accounts openings for day-to-day documentation, records, and finance coordination in a manufacturing environment.',
    salary: 'Compensation on request',
    tags: ['accounts', 'finance', 'dehradun'],
  },
  {
    id: 'JYBL-2619',
    title: 'Manufacturing Operator',
    company: 'Confidential Pharma Employer',
    sector: 'Pharma Operations',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '2-10 yrs',
    salaryRange: 'Compensation on request',
    type: 'Full-time',
    openings: 37,
    status: 'Open',
    location: 'Selaqui, Dehradun, Uttarakhand',
    description: 'Operator openings across coating, granulation, compression, capsule, dry syrup, vacuum filling, alu-alu, strip blister, and L-Mack machine operations. Eligibility typically includes ITI, 10th, or 12th based on machine and department fit.',
    salary: 'Compensation on request',
    tags: ['operator', 'compression', 'granulation'],
  },
  {
    id: 'JYBL-2601',
    title: 'Talent Acquisition Executive',
    company: 'Oaklane Staffing',
    sector: 'Recruitment & HR',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '\u20B92.4L-\u20B93.6L',
    type: 'Full-time',
    openings: 2,
    status: 'Interviewing',
    location: 'Dehradun, Uttarakhand',
    description: 'Handle candidate sourcing, first-level screening, and daily interview coordination for active hiring mandates.',
    salary: '\u20B92.4L-\u20B93.6L',
    tags: ['recruitment', 'talent acquisition', 'dehradun'],
  },
  {
    id: 'JYBL-2602',
    title: 'HR Recruiter',
    company: 'PeopleBridge Services',
    sector: 'Recruitment & HR',
    city: 'Noida',
    locationType: 'Hybrid',
    experience: '1-2 yrs',
    salaryRange: '\u20B92.4L-\u20B93.4L',
    type: 'Full-time',
    openings: 3,
    status: 'Open',
    location: 'Noida, Uttar Pradesh',
    description: 'Work on sourcing, profile screening, interview scheduling, and candidate follow-up for mid-volume hiring.',
    salary: '\u20B92.4L-\u20B93.4L',
    tags: ['hr recruiter', 'screening', 'noida'],
  },
  {
    id: 'JYBL-2603',
    title: 'Business Development Associate',
    company: 'LeadSprint Solutions',
    sector: 'Sales & Business Development',
    city: 'Gurugram',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '\u20B93.0L-\u20B94.5L',
    type: 'Full-time',
    openings: 2,
    status: 'Open',
    location: 'Gurugram, Haryana',
    description: 'Support outbound lead generation, client follow-up, and daily business development reporting for a growing team.',
    salary: '\u20B93.0L-\u20B94.5L',
    tags: ['bda', 'sales', 'gurugram'],
  },
  {
    id: 'JYBL-2604',
    title: 'Customer Support Executive',
    company: 'AssistEdge Global',
    sector: 'Customer Support',
    city: 'Chandigarh',
    locationType: 'On-site',
    experience: '0-2 yrs',
    salaryRange: '\u20B92.0L-\u20B93.2L',
    type: 'Full-time',
    openings: 4,
    status: 'Interviewing',
    location: 'Chandigarh',
    description: 'Manage inbound queries, ticket follow-up, and customer issue resolution with clear escalation support.',
    salary: '\u20B92.0L-\u20B93.2L',
    tags: ['customer support', 'voice process', 'chandigarh'],
  },
  {
    id: 'JYBL-2605',
    title: 'Operations Coordinator',
    company: 'Routewell Logistics',
    sector: 'Operations & Coordination',
    city: 'Jaipur',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '\u20B92.8L-\u20B94.0L',
    type: 'Full-time',
    openings: 2,
    status: 'Open',
    location: 'Jaipur, Rajasthan',
    description: 'Coordinate daily dispatch updates, reporting, and cross-team follow-up for service and operations workflows.',
    salary: '\u20B92.8L-\u20B94.0L',
    tags: ['operations', 'coordination', 'jaipur'],
  },
  {
    id: 'JYBL-2606',
    title: 'Front Desk and Admin Executive',
    company: 'Shivalik Residency',
    sector: 'Administration',
    city: 'Mohali',
    locationType: 'On-site',
    experience: '1-2 yrs',
    salaryRange: '\u20B92.0L-\u20B92.8L',
    type: 'Full-time',
    openings: 1,
    status: 'Open',
    location: 'Mohali, Punjab',
    description: 'Handle front-desk coordination, visitor support, basic documentation, and office administration tasks.',
    salary: '\u20B92.0L-\u20B92.8L',
    tags: ['front desk', 'admin', 'mohali'],
  },
  {
    id: 'JYBL-2607',
    title: 'MIS Executive',
    company: 'DataCraft Business Services',
    sector: 'MIS & Reporting',
    city: 'Lucknow',
    locationType: 'Hybrid',
    experience: '1-3 yrs',
    salaryRange: '\u20B92.6L-\u20B93.8L',
    type: 'Full-time',
    openings: 2,
    status: 'Interviewing',
    location: 'Lucknow, Uttar Pradesh',
    description: 'Prepare daily reports, maintain dashboards, and support management with clean data tracking and Excel-based MIS work.',
    salary: '\u20B92.6L-\u20B93.8L',
    tags: ['mis', 'excel', 'lucknow'],
  },
  {
    id: 'JYBL-2608',
    title: 'Digital Marketing Executive',
    company: 'PixelRoot Media',
    sector: 'Marketing',
    city: 'Delhi',
    locationType: 'Hybrid',
    experience: '1-3 yrs',
    salaryRange: '\u20B93.0L-\u20B94.2L',
    type: 'Full-time',
    openings: 2,
    status: 'Open',
    location: 'Delhi',
    description: 'Work on social media execution, campaign coordination, content planning, and basic performance reporting.',
    salary: '\u20B93.0L-\u20B94.2L',
    tags: ['digital marketing', 'performance', 'delhi'],
  },
  {
    id: 'JYBL-2609',
    title: 'Accounts Executive',
    company: 'LedgerPoint Advisors',
    sector: 'Accounts & Finance',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '\u20B92.8L-\u20B94.0L',
    type: 'Full-time',
    openings: 1,
    status: 'Open',
    location: 'Dehradun, Uttarakhand',
    description: 'Support billing, voucher entries, reconciliations, and monthly accounting coordination for day-to-day finance work.',
    salary: '\u20B92.8L-\u20B94.0L',
    tags: ['accounts', 'finance', 'dehradun'],
  },
  {
    id: 'JYBL-2610',
    title: 'Junior Full-Stack Developer',
    company: 'NexaBuild Systems',
    sector: 'Technology',
    city: 'Noida',
    locationType: 'Hybrid',
    experience: '1-2 yrs',
    salaryRange: '\u20B93.5L-\u20B95.0L',
    type: 'Full-time',
    openings: 1,
    status: 'Interviewing',
    location: 'Noida, Uttar Pradesh',
    description: 'Build and maintain internal web modules using React and Node, with hands-on support from a small product team.',
    salary: '\u20B93.5L-\u20B95.0L',
    tags: ['developer', 'react', 'noida'],
  },
  {
    id: 'JYBL-2611',
    title: 'UI/UX Designer',
    company: 'Studio Current',
    sector: 'Design',
    city: 'Gurugram',
    locationType: 'Hybrid',
    experience: '1-3 yrs',
    salaryRange: '\u20B93.0L-\u20B94.5L',
    type: 'Full-time',
    openings: 1,
    status: 'Open',
    location: 'Gurugram, Haryana',
    description: 'Create interface layouts, wireframes, and design handoff assets for web and mobile product journeys.',
    salary: '\u20B93.0L-\u20B94.5L',
    tags: ['ui ux', 'design', 'gurugram'],
  },
  {
    id: 'JYBL-2612',
    title: 'Sales Executive',
    company: 'UrbanShelf Retail',
    sector: 'Sales & Retail',
    city: 'Chandigarh',
    locationType: 'On-site',
    experience: '0-2 yrs',
    salaryRange: '\u20B92.4L-\u20B93.6L',
    type: 'Full-time',
    openings: 3,
    status: 'Offer',
    location: 'Chandigarh',
    description: 'Handle store-level sales conversations, lead follow-up, and walk-in customer support for a fast-moving retail team.',
    salary: '\u20B92.4L-\u20B93.6L',
    tags: ['sales', 'retail', 'chandigarh'],
  },
];

const seedContent = [
  {
    id: 'home-hero',
    title: 'Homepage Hero',
    body: 'Connecting innovative companies with the talent that drives excellence and growth.',
    mediaUrl: null,
  },
  {
    id: 'services-summary',
    title: 'Services Summary',
    body: 'Practical hiring support across sectors we can genuinely serve well.',
    mediaUrl: null,
  },
  {
    id: 'contact-summary',
    title: 'Contact Summary',
    body: 'Connect with our hiring desk for mandates, enquiries, and regional hiring coordination.',
    mediaUrl: null,
  },
];

async function main() {
  for (const job of seedJobs) {
    await prisma.job.upsert({
      where: { id: job.id },
      update: job,
      create: job,
    });
  }

  for (const item of seedContent) {
    await prisma.siteContent.upsert({
      where: { id: item.id },
      update: item,
      create: item,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('Seed complete');
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });

