const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const seedJobs = [
  {
    id: 'JYBL-2601',
    title: 'Talent Acquisition Executive',
    company: 'Oaklane Staffing',
    sector: 'Recruitment & HR',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '₹2.4L-₹3.6L',
    type: 'Full-time',
    openings: 2,
    status: 'Interviewing',
    location: 'Dehradun, Uttarakhand',
    description: 'Handle candidate sourcing, first-level screening, and daily interview coordination for active hiring mandates.',
    salary: '₹2.4L-₹3.6L',
    tags: ['recruitment', 'talent acquisition', 'dehradun'],
  },
  {
    id: 'JYBL-2602',
    title: 'HR Recruiter',
    company: 'PeopleBridge Services',
    sector: 'Recruitment & HR',
    city: 'Noida',
    locationType: 'Hybrid',
    experience: '1-2 yrs',
    salaryRange: '₹2.4L-₹3.4L',
    type: 'Full-time',
    openings: 3,
    status: 'Open',
    location: 'Noida, Uttar Pradesh',
    description: 'Work on sourcing, profile screening, interview scheduling, and candidate follow-up for mid-volume hiring.',
    salary: '₹2.4L-₹3.4L',
    tags: ['hr recruiter', 'screening', 'noida'],
  },
  {
    id: 'JYBL-2603',
    title: 'Business Development Associate',
    company: 'LeadSprint Solutions',
    sector: 'Sales & Business Development',
    city: 'Gurugram',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '₹3.0L-₹4.5L',
    type: 'Full-time',
    openings: 2,
    status: 'Open',
    location: 'Gurugram, Haryana',
    description: 'Support outbound lead generation, client follow-up, and daily business development reporting for a growing team.',
    salary: '₹3.0L-₹4.5L',
    tags: ['bda', 'sales', 'gurugram'],
  },
  {
    id: 'JYBL-2604',
    title: 'Customer Support Executive',
    company: 'AssistEdge Global',
    sector: 'Customer Support',
    city: 'Chandigarh',
    locationType: 'On-site',
    experience: '0-2 yrs',
    salaryRange: '₹2.0L-₹3.2L',
    type: 'Full-time',
    openings: 4,
    status: 'Interviewing',
    location: 'Chandigarh',
    description: 'Manage inbound queries, ticket follow-up, and customer issue resolution with clear escalation support.',
    salary: '₹2.0L-₹3.2L',
    tags: ['customer support', 'voice process', 'chandigarh'],
  },
  {
    id: 'JYBL-2605',
    title: 'Operations Coordinator',
    company: 'Routewell Logistics',
    sector: 'Operations & Coordination',
    city: 'Jaipur',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '₹2.8L-₹4.0L',
    type: 'Full-time',
    openings: 2,
    status: 'Open',
    location: 'Jaipur, Rajasthan',
    description: 'Coordinate daily dispatch updates, reporting, and cross-team follow-up for service and operations workflows.',
    salary: '₹2.8L-₹4.0L',
    tags: ['operations', 'coordination', 'jaipur'],
  },
  {
    id: 'JYBL-2606',
    title: 'Front Desk and Admin Executive',
    company: 'Shivalik Residency',
    sector: 'Administration',
    city: 'Mohali',
    locationType: 'On-site',
    experience: '1-2 yrs',
    salaryRange: '₹2.0L-₹2.8L',
    type: 'Full-time',
    openings: 1,
    status: 'Open',
    location: 'Mohali, Punjab',
    description: 'Handle front-desk coordination, visitor support, basic documentation, and office administration tasks.',
    salary: '₹2.0L-₹2.8L',
    tags: ['front desk', 'admin', 'mohali'],
  },
  {
    id: 'JYBL-2607',
    title: 'MIS Executive',
    company: 'DataCraft Business Services',
    sector: 'MIS & Reporting',
    city: 'Lucknow',
    locationType: 'Hybrid',
    experience: '1-3 yrs',
    salaryRange: '₹2.6L-₹3.8L',
    type: 'Full-time',
    openings: 2,
    status: 'Interviewing',
    location: 'Lucknow, Uttar Pradesh',
    description: 'Prepare daily reports, maintain dashboards, and support management with clean data tracking and Excel-based MIS work.',
    salary: '₹2.6L-₹3.8L',
    tags: ['mis', 'excel', 'lucknow'],
  },
  {
    id: 'JYBL-2608',
    title: 'Digital Marketing Executive',
    company: 'PixelRoot Media',
    sector: 'Marketing',
    city: 'Delhi',
    locationType: 'Hybrid',
    experience: '1-3 yrs',
    salaryRange: '₹3.0L-₹4.2L',
    type: 'Full-time',
    openings: 2,
    status: 'Open',
    location: 'Delhi',
    description: 'Work on social media execution, campaign coordination, content planning, and basic performance reporting.',
    salary: '₹3.0L-₹4.2L',
    tags: ['digital marketing', 'performance', 'delhi'],
  },
  {
    id: 'JYBL-2609',
    title: 'Accounts Executive',
    company: 'LedgerPoint Advisors',
    sector: 'Accounts & Finance',
    city: 'Dehradun',
    locationType: 'On-site',
    experience: '1-3 yrs',
    salaryRange: '₹2.8L-₹4.0L',
    type: 'Full-time',
    openings: 1,
    status: 'Open',
    location: 'Dehradun, Uttarakhand',
    description: 'Support billing, voucher entries, reconciliations, and monthly accounting coordination for day-to-day finance work.',
    salary: '₹2.8L-₹4.0L',
    tags: ['accounts', 'finance', 'dehradun'],
  },
  {
    id: 'JYBL-2610',
    title: 'Junior Full-Stack Developer',
    company: 'NexaBuild Systems',
    sector: 'Technology',
    city: 'Noida',
    locationType: 'Hybrid',
    experience: '1-2 yrs',
    salaryRange: '₹3.5L-₹5.0L',
    type: 'Full-time',
    openings: 1,
    status: 'Interviewing',
    location: 'Noida, Uttar Pradesh',
    description: 'Build and maintain internal web modules using React and Node, with hands-on support from a small product team.',
    salary: '₹3.5L-₹5.0L',
    tags: ['developer', 'react', 'noida'],
  },
  {
    id: 'JYBL-2611',
    title: 'UI/UX Designer',
    company: 'Studio Current',
    sector: 'Design',
    city: 'Gurugram',
    locationType: 'Hybrid',
    experience: '1-3 yrs',
    salaryRange: '₹3.0L-₹4.5L',
    type: 'Full-time',
    openings: 1,
    status: 'Open',
    location: 'Gurugram, Haryana',
    description: 'Create interface layouts, wireframes, and design handoff assets for web and mobile product journeys.',
    salary: '₹3.0L-₹4.5L',
    tags: ['ui ux', 'design', 'gurugram'],
  },
  {
    id: 'JYBL-2612',
    title: 'Sales Executive',
    company: 'UrbanShelf Retail',
    sector: 'Sales & Retail',
    city: 'Chandigarh',
    locationType: 'On-site',
    experience: '0-2 yrs',
    salaryRange: '₹2.4L-₹3.6L',
    type: 'Full-time',
    openings: 3,
    status: 'Offer',
    location: 'Chandigarh',
    description: 'Handle store-level sales conversations, lead follow-up, and walk-in customer support for a fast-moving retail team.',
    salary: '₹2.4L-₹3.6L',
    tags: ['sales', 'retail', 'chandigarh'],
  },
];

const seedContent = [
  {
    id: 'home-hero',
    title: 'Homepage Hero',
    body: 'Connecting innovative companies with the talent that drives excellence and growth.',
    mediaUrl: null,
  },
  {
    id: 'services-summary',
    title: 'Services Summary',
    body: 'Practical hiring support across sectors we can genuinely serve well.',
    mediaUrl: null,
  },
  {
    id: 'contact-summary',
    title: 'Contact Summary',
    body: 'Connect with our hiring desk for mandates, enquiries, and regional hiring coordination.',
    mediaUrl: null,
  },
];

async function main() {
  for (const job of seedJobs) {
    await prisma.job.upsert({
      where: { id: job.id },
      update: job,
      create: job,
    });
  }

  for (const item of seedContent) {
    await prisma.siteContent.upsert({
      where: { id: item.id },
      update: item,
      create: item,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('Seed complete');
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
