export type Job = {
  id: string;
  title: string;
  company: string;
  sector: string;
  city: string;
  locationType: "On-site" | "Hybrid" | "Remote";
  experience: string;
  salaryRange: string;
  type: "Full-time" | "Contract" | "Internship";
  openings: number;
  postedAt: string;
  status: "Open" | "Interviewing" | "Offer" | "Closed";
};

export const jobs: Job[] = [
  {
    id: "JYBL-2639",
    title: "Production Executive",
    company: "Confidential Food Manufacturing Employer",
    sector: "Production",
    city: "Delhi / Sonipat",
    locationType: "On-site",
    experience: "Chocolate or food industry experience preferred",
    salaryRange: "INR 40,000 / month",
    type: "Full-time",
    openings: 4,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2640",
    title: "Technician",
    company: "Confidential Food Manufacturing Employer",
    sector: "Maintenance & Technical Operations",
    city: "Delhi / Sonipat",
    locationType: "On-site",
    experience: "Chocolate or food industry experience preferred",
    salaryRange: "INR 40,000 / month",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2641",
    title: "Operator",
    company: "Confidential Food Manufacturing Employer",
    sector: "Production",
    city: "Delhi / Sonipat",
    locationType: "On-site",
    experience: "Fresher",
    salaryRange: "INR 15,000 / month",
    type: "Full-time",
    openings: 10,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2642",
    title: "Production Executive - Fresher Shift",
    company: "Confidential Food Manufacturing Employer",
    sector: "Production",
    city: "Delhi / Sonipat",
    locationType: "On-site",
    experience: "Fresher",
    salaryRange: "INR 20,000 / month",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2643",
    title: "Production Executive - Additional Fresher Shift",
    company: "Confidential Food Manufacturing Employer",
    sector: "Production",
    city: "Delhi / Sonipat",
    locationType: "On-site",
    experience: "Fresher",
    salaryRange: "INR 20,000 / month",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2644",
    title: "Accounts Executive",
    company: "Confidential Food Manufacturing Employer",
    sector: "Accounts & Finance",
    city: "Delhi / Sonipat",
    locationType: "On-site",
    experience: "2-3 yrs",
    salaryRange: "INR 20,000 / month",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2620",
    title: "QC Chemist",
    company: "Confidential Life Sciences Employer",
    sector: "Quality Control",
    city: "Dehradun",
    locationType: "On-site",
    experience: "4-5 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2621",
    title: "Stability Executive",
    company: "Confidential Life Sciences Employer",
    sector: "Quality Control",
    city: "Dehradun",
    locationType: "On-site",
    experience: "4-6 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2622",
    title: "QC Micro Executive / Sr. Officer",
    company: "Confidential Life Sciences Employer",
    sector: "Quality Control",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-6 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 6,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2623",
    title: "QC Micro Assistant Manager",
    company: "Confidential Life Sciences Employer",
    sector: "Quality Control",
    city: "Dehradun",
    locationType: "On-site",
    experience: "9-12 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2624",
    title: "IPQA Executive",
    company: "Confidential Life Sciences Employer",
    sector: "Quality Assurance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-3 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 3,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2625",
    title: "3 PCS Filling Sealing Operator",
    company: "Confidential Life Sciences Employer",
    sector: "Production",
    city: "Dehradun",
    locationType: "On-site",
    experience: "4-6 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2626",
    title: "Production Fresher / Sr. Officer",
    company: "Confidential Life Sciences Employer",
    sector: "Production",
    city: "Dehradun",
    locationType: "On-site",
    experience: "0-4 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2627",
    title: "IPQC Chemist",
    company: "Confidential Life Sciences Employer",
    sector: "Production",
    city: "Dehradun",
    locationType: "On-site",
    experience: "Freshers / Experienced",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 3,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2628",
    title: "Shift Engineer / Jr. Operator",
    company: "Confidential Life Sciences Employer",
    sector: "Production",
    city: "Dehradun",
    locationType: "On-site",
    experience: "BFS-FS / Romanlack experience",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 4,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2629",
    title: "Jr. Officer / Executive - Art Work",
    company: "Confidential Life Sciences Employer",
    sector: "Graphic Design",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-8 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2630",
    title: "Assistant Manager - International & BD",
    company: "Confidential Life Sciences Employer",
    sector: "International Business Development",
    city: "Dehradun",
    locationType: "On-site",
    experience: "5-8 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2631",
    title: "Back Office Executive - Marketing & BD",
    company: "Confidential Life Sciences Employer",
    sector: "Marketing & Business Development",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-3 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 4,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2632",
    title: "Packaging Operator",
    company: "Confidential Life Sciences Employer",
    sector: "Packaging",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-4 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2633",
    title: "Procurement Executive",
    company: "Confidential Life Sciences Employer",
    sector: "Procurement",
    city: "Dehradun",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2634",
    title: "Receptionist",
    company: "Confidential Life Sciences Employer",
    sector: "HR & Administration",
    city: "Dehradun",
    locationType: "On-site",
    experience: "0-2 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2635",
    title: "CA - Accounts & Finance",
    company: "Confidential Life Sciences Employer",
    sector: "Accounts & Finance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "8-15 yrs / 10-15 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2636",
    title: "PPIC Officer",
    company: "Confidential Life Sciences Employer",
    sector: "Planning & Inventory Control",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-4 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2637",
    title: "ETP Incharge",
    company: "Confidential Life Sciences Employer",
    sector: "Engineering & Maintenance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "4-5 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-31",
    status: "Open",
  },
  {
    id: "JYBL-2638",
    title: "Trainee Assistant (ITI) - Bottle Pack",
    company: "Confidential Life Sciences Employer",
    sector: "Packaging",
    city: "Dehradun",
    locationType: "On-site",
    experience: "Fresher",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-31",
    status: "Open",
  },  {
    id: "JYBL-2613",
    title: "Production Officer / Executive / Assistant Manager",
    company: "Confidential Pharma Employer",
    sector: "Pharma Manufacturing",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-10 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 8,
    postedAt: "2026-03-30",
    status: "Open",
  },
  {
    id: "JYBL-2614",
    title: "Maintenance Engineer",
    company: "Confidential Pharma Employer",
    sector: "Engineering & Maintenance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-10 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 7,
    postedAt: "2026-03-30",
    status: "Open",
  },
  {
    id: "JYBL-2615",
    title: "QA Executive / Documentation Executive",
    company: "Confidential Pharma Employer",
    sector: "Quality Assurance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-10 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 10,
    postedAt: "2026-03-30",
    status: "Open",
  },
  {
    id: "JYBL-2616",
    title: "QC Analyst",
    company: "Confidential Pharma Employer",
    sector: "Quality Control",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-10 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 20,
    postedAt: "2026-03-30",
    status: "Open",
  },
  {
    id: "JYBL-2617",
    title: "HR Documentation Executive",
    company: "Confidential Pharma Employer",
    sector: "HR & Administration",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-10 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-30",
    status: "Open",
  },
  {
    id: "JYBL-2618",
    title: "Accounts Executive",
    company: "Confidential Pharma Employer",
    sector: "Accounts & Finance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-10 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 3,
    postedAt: "2026-03-30",
    status: "Open",
  },
  {
    id: "JYBL-2619",
    title: "Manufacturing Operator",
    company: "Confidential Pharma Employer",
    sector: "Pharma Operations",
    city: "Dehradun",
    locationType: "On-site",
    experience: "2-10 yrs",
    salaryRange: "Compensation on request",
    type: "Full-time",
    openings: 37,
    postedAt: "2026-03-30",
    status: "Open",
  },
  {
    id: "JYBL-2601",
    title: "Talent Acquisition Executive",
    company: "Oaklane Staffing",
    sector: "Recruitment & HR",
    city: "Dehradun",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "\u20B92.4L-\u20B93.6L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-25",
    status: "Interviewing",
  },
  {
    id: "JYBL-2602",
    title: "HR Recruiter",
    company: "PeopleBridge Services",
    sector: "Recruitment & HR",
    city: "Noida",
    locationType: "Hybrid",
    experience: "1-2 yrs",
    salaryRange: "\u20B92.4L-\u20B93.4L",
    type: "Full-time",
    openings: 3,
    postedAt: "2026-03-24",
    status: "Open",
  },
  {
    id: "JYBL-2603",
    title: "Business Development Associate",
    company: "LeadSprint Solutions",
    sector: "Sales & Business Development",
    city: "Gurugram",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "\u20B93.0L-\u20B94.5L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-24",
    status: "Open",
  },
  {
    id: "JYBL-2604",
    title: "Customer Support Executive",
    company: "AssistEdge Global",
    sector: "Customer Support",
    city: "Chandigarh",
    locationType: "On-site",
    experience: "0-2 yrs",
    salaryRange: "\u20B92.0L-\u20B93.2L",
    type: "Full-time",
    openings: 4,
    postedAt: "2026-03-23",
    status: "Interviewing",
  },
  {
    id: "JYBL-2605",
    title: "Operations Coordinator",
    company: "Routewell Logistics",
    sector: "Operations & Coordination",
    city: "Jaipur",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "\u20B92.8L-\u20B94.0L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-23",
    status: "Open",
  },
  {
    id: "JYBL-2606",
    title: "Front Desk and Admin Executive",
    company: "Shivalik Residency",
    sector: "Administration",
    city: "Mohali",
    locationType: "On-site",
    experience: "1-2 yrs",
    salaryRange: "\u20B92.0L-\u20B92.8L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-22",
    status: "Open",
  },
  {
    id: "JYBL-2607",
    title: "MIS Executive",
    company: "DataCraft Business Services",
    sector: "MIS & Reporting",
    city: "Lucknow",
    locationType: "Hybrid",
    experience: "1-3 yrs",
    salaryRange: "\u20B92.6L-\u20B93.8L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-22",
    status: "Interviewing",
  },
  {
    id: "JYBL-2608",
    title: "Digital Marketing Executive",
    company: "PixelRoot Media",
    sector: "Marketing",
    city: "Delhi",
    locationType: "Hybrid",
    experience: "1-3 yrs",
    salaryRange: "\u20B93.0L-\u20B94.2L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-21",
    status: "Open",
  },
  {
    id: "JYBL-2609",
    title: "Accounts Executive",
    company: "LedgerPoint Advisors",
    sector: "Accounts & Finance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "\u20B92.8L-\u20B94.0L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-21",
    status: "Open",
  },
  {
    id: "JYBL-2610",
    title: "Junior Full-Stack Developer",
    company: "NexaBuild Systems",
    sector: "Technology",
    city: "Noida",
    locationType: "Hybrid",
    experience: "1-2 yrs",
    salaryRange: "\u20B93.5L-\u20B95.0L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-20",
    status: "Interviewing",
  },
  {
    id: "JYBL-2611",
    title: "UI/UX Designer",
    company: "Studio Current",
    sector: "Design",
    city: "Gurugram",
    locationType: "Hybrid",
    experience: "1-3 yrs",
    salaryRange: "\u20B93.0L-\u20B94.5L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-20",
    status: "Open",
  },
  {
    id: "JYBL-2612",
    title: "Sales Executive",
    company: "UrbanShelf Retail",
    sector: "Sales & Retail",
    city: "Chandigarh",
    locationType: "On-site",
    experience: "0-2 yrs",
    salaryRange: "\u20B92.4L-\u20B93.6L",
    type: "Full-time",
    openings: 3,
    postedAt: "2026-03-19",
    status: "Offer",
  },
];

export const candidates = [
  { name: "Priya Narang", role: "UI/UX Designer", stage: "Portfolio review", eta: "Today" },
  { name: "Rohit Bisht", role: "Junior Full-Stack Developer", stage: "Technical round", eta: "In 2h" },
  { name: "Naina Bhandari", role: "HR Recruiter", stage: "Hiring manager", eta: "Tomorrow" },
  { name: "Arjun Mehta", role: "MIS Executive", stage: "Offer discussion", eta: "Awaiting" },
  { name: "Sakshi Rana", role: "Digital Marketing Executive", stage: "Final interview", eta: "Thu" },
];

export const pipeline = {
  inbound: 342,
  shortlisted: 102,
  interviewing: 57,
  offers: 14,
  onTimeInterviewRate: 0.93,
};

export const opsChecklist = [
  "Review recruiter shortlist for Dehradun staffing roles",
  "Share interview schedule for Noida developer mandate",
  "Confirm salary alignment for Chandigarh support openings",
  "Close follow-up on Gurugram design and sales roles",
];

