export type Job = {
  id: string;
  title: string;
  company: string;
  sector: string;
  city: string;
  locationType: "On-site" | "Hybrid" | "Remote";
  experience: string;
  salaryRange: string;
  type: "Full-time" | "Contract" | "Internship";
  openings: number;
  postedAt: string;
  status: "Open" | "Interviewing" | "Offer" | "Closed";
};

export const jobs: Job[] = [
  {
    id: "JYBL-2601",
    title: "Talent Acquisition Executive",
    company: "Oaklane Staffing",
    sector: "Recruitment & HR",
    city: "Dehradun",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "₹2.4L-₹3.6L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-25",
    status: "Interviewing",
  },
  {
    id: "JYBL-2602",
    title: "HR Recruiter",
    company: "PeopleBridge Services",
    sector: "Recruitment & HR",
    city: "Noida",
    locationType: "Hybrid",
    experience: "1-2 yrs",
    salaryRange: "₹2.4L-₹3.4L",
    type: "Full-time",
    openings: 3,
    postedAt: "2026-03-24",
    status: "Open",
  },
  {
    id: "JYBL-2603",
    title: "Business Development Associate",
    company: "LeadSprint Solutions",
    sector: "Sales & Business Development",
    city: "Gurugram",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "₹3.0L-₹4.5L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-24",
    status: "Open",
  },
  {
    id: "JYBL-2604",
    title: "Customer Support Executive",
    company: "AssistEdge Global",
    sector: "Customer Support",
    city: "Chandigarh",
    locationType: "On-site",
    experience: "0-2 yrs",
    salaryRange: "₹2.0L-₹3.2L",
    type: "Full-time",
    openings: 4,
    postedAt: "2026-03-23",
    status: "Interviewing",
  },
  {
    id: "JYBL-2605",
    title: "Operations Coordinator",
    company: "Routewell Logistics",
    sector: "Operations & Coordination",
    city: "Jaipur",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "₹2.8L-₹4.0L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-23",
    status: "Open",
  },
  {
    id: "JYBL-2606",
    title: "Front Desk and Admin Executive",
    company: "Shivalik Residency",
    sector: "Administration",
    city: "Mohali",
    locationType: "On-site",
    experience: "1-2 yrs",
    salaryRange: "₹2.0L-₹2.8L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-22",
    status: "Open",
  },
  {
    id: "JYBL-2607",
    title: "MIS Executive",
    company: "DataCraft Business Services",
    sector: "MIS & Reporting",
    city: "Lucknow",
    locationType: "Hybrid",
    experience: "1-3 yrs",
    salaryRange: "₹2.6L-₹3.8L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-22",
    status: "Interviewing",
  },
  {
    id: "JYBL-2608",
    title: "Digital Marketing Executive",
    company: "PixelRoot Media",
    sector: "Marketing",
    city: "Delhi",
    locationType: "Hybrid",
    experience: "1-3 yrs",
    salaryRange: "₹3.0L-₹4.2L",
    type: "Full-time",
    openings: 2,
    postedAt: "2026-03-21",
    status: "Open",
  },
  {
    id: "JYBL-2609",
    title: "Accounts Executive",
    company: "LedgerPoint Advisors",
    sector: "Accounts & Finance",
    city: "Dehradun",
    locationType: "On-site",
    experience: "1-3 yrs",
    salaryRange: "₹2.8L-₹4.0L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-21",
    status: "Open",
  },
  {
    id: "JYBL-2610",
    title: "Junior Full-Stack Developer",
    company: "NexaBuild Systems",
    sector: "Technology",
    city: "Noida",
    locationType: "Hybrid",
    experience: "1-2 yrs",
    salaryRange: "₹3.5L-₹5.0L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-20",
    status: "Interviewing",
  },
  {
    id: "JYBL-2611",
    title: "UI/UX Designer",
    company: "Studio Current",
    sector: "Design",
    city: "Gurugram",
    locationType: "Hybrid",
    experience: "1-3 yrs",
    salaryRange: "₹3.0L-₹4.5L",
    type: "Full-time",
    openings: 1,
    postedAt: "2026-03-20",
    status: "Open",
  },
  {
    id: "JYBL-2612",
    title: "Sales Executive",
    company: "UrbanShelf Retail",
    sector: "Sales & Retail",
    city: "Chandigarh",
    locationType: "On-site",
    experience: "0-2 yrs",
    salaryRange: "₹2.4L-₹3.6L",
    type: "Full-time",
    openings: 3,
    postedAt: "2026-03-19",
    status: "Offer",
  },
];

export const candidates = [
  { name: "Priya Narang", role: "UI/UX Designer", stage: "Portfolio review", eta: "Today" },
  { name: "Rohit Bisht", role: "Junior Full-Stack Developer", stage: "Technical round", eta: "In 2h" },
  { name: "Naina Bhandari", role: "HR Recruiter", stage: "Hiring manager", eta: "Tomorrow" },
  { name: "Arjun Mehta", role: "MIS Executive", stage: "Offer discussion", eta: "Awaiting" },
  { name: "Sakshi Rana", role: "Digital Marketing Executive", stage: "Final interview", eta: "Thu" },
];

export const pipeline = {
  inbound: 342,
  shortlisted: 102,
  interviewing: 57,
  offers: 14,
  onTimeInterviewRate: 0.93,
};

export const opsChecklist = [
  "Review recruiter shortlist for Dehradun staffing roles",
  "Share interview schedule for Noida developer mandate",
  "Confirm salary alignment for Chandigarh support openings",
  "Close follow-up on Gurugram design and sales roles",
];
